---
title: "A14: Shiny with Maps"
author: "John Hope (jah9kqn)"
date: "Due Date: 11:59pm, Apr 3"
output: ioslides_presentation
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(ggmap)
library(shiny)
```

## Individual Homework

   - "I pledge that I have neither given nor received help on this assignment."

## Map Plot

```{r}
# API Key
register_google(key = "AIzaSyDf5JlxC2iLZwmUE2KfFIUoMd4e5lnsnu4")
    
# ui fluid page with slider zoom input
ui = fluidPage(sliderInput("zooms", label = "Zoom:", min = 5, max = 18, value = 10, step = 1),
               plotOutput("cityzoom"))

# server to create the map plot with variable zoom
server = function(input, output){
    nyc <- geocode("New York")
    output$cityzoom <- renderPlot({
        ggmap(get_map(nyc, zoom=input$zooms)) + xlab('Longitude') + ylab('Latitude') + ggtitle('New York, NY')
        })
    }

# create shiny app
shinyApp(ui = ui, server = server, options = list(height = 600)) # if you like, change the height value.
```